<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	 <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.0" />
	 <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PTLMFGPLUS.LIB\PTLMFGPLUS.LIB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="S_07_RM\" />
  </ItemGroup>

</Project>
